### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by destag** [destag/at-date#1]
Add more pytest tests into test/test_atdate.py

**Comment by pjbollinger** [comment]
I would like to work on this!

**Comment by destag** [comment]
@pjbollinger Thanks! As you can see I'm using pytest for testing.

Don't worry if some tests  don't pass, as code can has some bugs.

**Comment by pjbollinger** [comment]
Yep, I see.

@destag, do you mind if I make code changes to fix bugs and make all tests pass? I will target 100% code coverage.

**Comment by destag** [comment]
It would be great. Thanks! :smile:

**Comment by destag** [comment]
I merged #8 
@pjbollinger  Thanks for your work. Moreover, if you have any ideas what can be added or changed feel free to open issue.
