### ISSUE TITLE
ISO 8601 compatibility 

### ISSUE THREAD

**Issue by andrzej3393** [destag/at-date#16]
I think that it would be nice to support dates and times in ISO 8601 format.

**Comment by andrzej3393** [comment]
The rules you have proposed look okay, I'll try to implement them :slightly_smiling_face:

**Comment by destag** [comment]
@andrzej3393 Of course, if you want you can implement it yourself. That would be very helpful. :)
I made some tests in branch `add/isodate`, so you can go from there and then PR to `master`.
